languages = [
    "TGLANG_LANGUAGE_OTHER",
    "TGLANG_LANGUAGE_1S_ENTERPRISE",
    "TGLANG_LANGUAGE_ABAP",
    "TGLANG_LANGUAGE_ACTIONSCRIPT",
    "TGLANG_LANGUAGE_ADA",
    "TGLANG_LANGUAGE_APACHE_GROOVY",
    "TGLANG_LANGUAGE_APEX",
    "TGLANG_LANGUAGE_APPLESCRIPT",
    "TGLANG_LANGUAGE_ASP",
    "TGLANG_LANGUAGE_ASSEMBLY",
    "TGLANG_LANGUAGE_AUTOHOTKEY",
    "TGLANG_LANGUAGE_AWK",
    "TGLANG_LANGUAGE_BASIC",
    "TGLANG_LANGUAGE_BATCH",
    "TGLANG_LANGUAGE_BISON",
    "TGLANG_LANGUAGE_C",
    "TGLANG_LANGUAGE_CLOJURE",
    "TGLANG_LANGUAGE_CMAKE",
    "TGLANG_LANGUAGE_COBOL",
    "TGLANG_LANGUAGE_COFFESCRIPT",
    "TGLANG_LANGUAGE_COMMON_LISP",
    "TGLANG_LANGUAGE_CPLUSPLUS",
    "TGLANG_LANGUAGE_CRYSTAL",
    "TGLANG_LANGUAGE_CSHARP",
    "TGLANG_LANGUAGE_CSS",
    "TGLANG_LANGUAGE_CSV",
    "TGLANG_LANGUAGE_D",
    "TGLANG_LANGUAGE_DART",
    "TGLANG_LANGUAGE_DELPHI",
    "TGLANG_LANGUAGE_DOCKER",
    "TGLANG_LANGUAGE_ELIXIR",
    "TGLANG_LANGUAGE_ELM",
    "TGLANG_LANGUAGE_ERLANG",
    "TGLANG_LANGUAGE_FIFT",
    "TGLANG_LANGUAGE_FORTH",
    "TGLANG_LANGUAGE_FORTRAN",
    "TGLANG_LANGUAGE_FSHARP",
    "TGLANG_LANGUAGE_FUNC",
    "TGLANG_LANGUAGE_GAMS",
    "TGLANG_LANGUAGE_GO",
    "TGLANG_LANGUAGE_GRADLE",
    "TGLANG_LANGUAGE_GRAPHQL",
    "TGLANG_LANGUAGE_HACK",
    "TGLANG_LANGUAGE_HASKELL",
    "TGLANG_LANGUAGE_HTML",
    "TGLANG_LANGUAGE_ICON",
    "TGLANG_LANGUAGE_IDL",
    "TGLANG_LANGUAGE_INI",
    "TGLANG_LANGUAGE_JAVA",
    "TGLANG_LANGUAGE_JAVASCRIPT",
    "TGLANG_LANGUAGE_JSON",
    "TGLANG_LANGUAGE_JULIA",
    "TGLANG_LANGUAGE_KEYMAN",
    "TGLANG_LANGUAGE_KOTLIN",
    "TGLANG_LANGUAGE_LATEX",
    "TGLANG_LANGUAGE_LISP",
    "TGLANG_LANGUAGE_LOGO",
    "TGLANG_LANGUAGE_LUA",
    "TGLANG_LANGUAGE_MAKEFILE",
    "TGLANG_LANGUAGE_MARKDOWN",
    "TGLANG_LANGUAGE_MATLAB",
    "TGLANG_LANGUAGE_NGINX",
    "TGLANG_LANGUAGE_NIM",
    "TGLANG_LANGUAGE_OBJECTIVE_C",
    "TGLANG_LANGUAGE_OCAML",
    "TGLANG_LANGUAGE_OPENEDGE_ABL",
    "TGLANG_LANGUAGE_PASCAL",
    "TGLANG_LANGUAGE_PERL",
    "TGLANG_LANGUAGE_PHP",
    "TGLANG_LANGUAGE_PL_SQL",
    "TGLANG_LANGUAGE_POWERSHELL",
    "TGLANG_LANGUAGE_PROLOG",
    "TGLANG_LANGUAGE_PROTOBUF",
    "TGLANG_LANGUAGE_PYTHON",
    "TGLANG_LANGUAGE_QML",
    "TGLANG_LANGUAGE_R",
    "TGLANG_LANGUAGE_RAKU",
    "TGLANG_LANGUAGE_REGEX",
    "TGLANG_LANGUAGE_RUBY",
    "TGLANG_LANGUAGE_RUST",
    "TGLANG_LANGUAGE_SAS",
    "TGLANG_LANGUAGE_SCALA",
    "TGLANG_LANGUAGE_SCHEME",
    "TGLANG_LANGUAGE_SHELL",
    "TGLANG_LANGUAGE_SMALLTALK",
    "TGLANG_LANGUAGE_SOLIDITY",
    "TGLANG_LANGUAGE_SQL",
    "TGLANG_LANGUAGE_SWIFT",
    "TGLANG_LANGUAGE_TCL",
    "TGLANG_LANGUAGE_TEXTILE",
    "TGLANG_LANGUAGE_TL",
    "TGLANG_LANGUAGE_TYPESCRIPT",
    "TGLANG_LANGUAGE_UNREALSCRIPT",
    "TGLANG_LANGUAGE_VALA",
    "TGLANG_LANGUAGE_VBSCRIPT",
    "TGLANG_LANGUAGE_VERILOG",
    "TGLANG_LANGUAGE_VISUAL_BASIC",
    "TGLANG_LANGUAGE_WOLFRAM",
    "TGLANG_LANGUAGE_XML",
    "TGLANG_LANGUAGE_YAML",
]

languages2num = {lang: i for i, lang in enumerate(languages)}

# These extensions were generated with AI + manually reviewed. Some errors may occur.
TGLANG_LANGUAGE_EXTENSIONS = {
    "TGLANG_LANGUAGE_1S_ENTERPRISE": [".1c", ".bsl", ".os"],
    "TGLANG_LANGUAGE_ABAP": [".abap"],
    "TGLANG_LANGUAGE_ACTIONSCRIPT": [".as"],
    "TGLANG_LANGUAGE_ADA": [".ada", ".adb", ".ads"],
    "TGLANG_LANGUAGE_APACHE_GROOVY": [".groovy"],
    "TGLANG_LANGUAGE_APEX": [".apex", ".cls", ".trigger"],
    "TGLANG_LANGUAGE_APPLESCRIPT": [".applescript", ".scpt"],
    "TGLANG_LANGUAGE_ASP": [".asp"],
    "TGLANG_LANGUAGE_ASSEMBLY": [".asm", ".s", ".as", ".x86", ".x64", ".arm", ".arm64"],
    "TGLANG_LANGUAGE_AUTOHOTKEY": [".ahk"],
    "TGLANG_LANGUAGE_AWK": [".awk"],
    "TGLANG_LANGUAGE_BASIC": [".bas", ".basic"],
    "TGLANG_LANGUAGE_BATCH": [".bat", ".cmd"],
    "TGLANG_LANGUAGE_BISON": [".y"],
    "TGLANG_LANGUAGE_C": [".c", ".h"],
    "TGLANG_LANGUAGE_CLOJURE": [".clj", ".cljs", ".cljc"],
    "TGLANG_LANGUAGE_CMAKE": ["CMakeLists.txt", ".cmake"],
    "TGLANG_LANGUAGE_COBOL": [".cob", ".cbl", ".cpy", ".cobol"],
    "TGLANG_LANGUAGE_COFFESCRIPT": [".coffee"],
    "TGLANG_LANGUAGE_COMMON_LISP": [".lisp", ".cl", ".l", ".mud"],
    "TGLANG_LANGUAGE_CPLUSPLUS": [".cpp", ".cxx", ".cc", ".h", ".hpp", ".hh", ".hxx"],
    "TGLANG_LANGUAGE_CRYSTAL": [".cr", ".crystal"],
    "TGLANG_LANGUAGE_CSHARP": [".cs"],
    "TGLANG_LANGUAGE_CSS": [".css"],
    "TGLANG_LANGUAGE_CSV": [".csv"],
    "TGLANG_LANGUAGE_D": [".d"],
    "TGLANG_LANGUAGE_DART": [".dart"],
    "TGLANG_LANGUAGE_DELPHI": [".pas", ".dpr", ".dpk", ".inc", ".delphi"],
    "TGLANG_LANGUAGE_DOCKER": ["dockerfile", ".dockerfile"],
    "TGLANG_LANGUAGE_ELIXIR": [".ex", ".exs", ".elixir"],
    "TGLANG_LANGUAGE_ELM": [".elm"],
    "TGLANG_LANGUAGE_ERLANG": [".erl", ".hrl"],
    "TGLANG_LANGUAGE_FIFT": [".fif"],
    "TGLANG_LANGUAGE_FORTH": [".fth", ".fs"],
    "TGLANG_LANGUAGE_FORTRAN": [".f", ".f90", ".f95"],
    "TGLANG_LANGUAGE_FSHARP": [".fs", ".fsi", ".fsx"],
    "TGLANG_LANGUAGE_FUNC": [".fc"],
    "TGLANG_LANGUAGE_GAMS": [".gms"],
    "TGLANG_LANGUAGE_GO": [".go"],
    "TGLANG_LANGUAGE_GRADLE": [".gradle"],
    "TGLANG_LANGUAGE_GRAPHQL": [".graphql", ".gql", ".graphqls"],
    "TGLANG_LANGUAGE_HACK": [".php", ".hh", ".hhi", ".hck"],
    "TGLANG_LANGUAGE_HASKELL": [".hs"],
    "TGLANG_LANGUAGE_HTML": [".html", ".htm", ".xhtml"],
    "TGLANG_LANGUAGE_ICON": [".icn", ".icon"],
    "TGLANG_LANGUAGE_IDL": [".pro"],
    "TGLANG_LANGUAGE_INI": [".ini"],
    "TGLANG_LANGUAGE_JAVA": [".java"],
    "TGLANG_LANGUAGE_JAVASCRIPT": [".js"],
    "TGLANG_LANGUAGE_JSON": [".json"],
    "TGLANG_LANGUAGE_JULIA": [".jl", ".julia"],
    "TGLANG_LANGUAGE_KEYMAN": [".kmn"],
    "TGLANG_LANGUAGE_KOTLIN": [".kt", ".kts"],
    "TGLANG_LANGUAGE_LATEX": [".tex", ".sty"],
    "TGLANG_LANGUAGE_LISP": [".el", ".l", ".lisp", ".cl"],
    "TGLANG_LANGUAGE_LOGO": [".logo"],
    "TGLANG_LANGUAGE_LUA": [".lua"],
    "TGLANG_LANGUAGE_MAKEFILE": ["Makefile", ".mk", ".makefile"],
    "TGLANG_LANGUAGE_MARKDOWN": [".md", ".markdown", ".mdown", ".mkd", ".mkdn"],
    "TGLANG_LANGUAGE_MATLAB": [".m"],
    "TGLANG_LANGUAGE_NGINX": [".conf", ".nginxconf"],
    "TGLANG_LANGUAGE_NIM": [".nim"],
    "TGLANG_LANGUAGE_OBJECTIVE_C": [".m", ".mm", ".h"],
    "TGLANG_LANGUAGE_OCAML": [".ml", ".mli"],
    "TGLANG_LANGUAGE_OPENEDGE_ABL": [".p", ".cls", ".openedge"],
    "TGLANG_LANGUAGE_PASCAL": [".pas", ".pp"],
    "TGLANG_LANGUAGE_PERL": [".pl", ".pm"],
    "TGLANG_LANGUAGE_PHP": [".php"],
    "TGLANG_LANGUAGE_PL_SQL": [".sql", ".pls", ".pkb", ".pks", ".plb"],
    "TGLANG_LANGUAGE_POWERSHELL": [".ps1", ".psm1", ".psd1"],
    "TGLANG_LANGUAGE_PROLOG": [".pro", ".P"],
    "TGLANG_LANGUAGE_PROTOBUF": [".proto"],
    "TGLANG_LANGUAGE_PYTHON": [".py"],
    "TGLANG_LANGUAGE_QML": [".qml"],
    "TGLANG_LANGUAGE_R": [".r", ".R"],
    "TGLANG_LANGUAGE_RAKU": [".raku", ".rakumod", ".rakutest"],
    "TGLANG_LANGUAGE_REGEX": [".regex", ".regexp", ".rgx", ".re", ".rex"],
    "TGLANG_LANGUAGE_RUBY": [".rb"],
    "TGLANG_LANGUAGE_RUST": [".rs"],
    "TGLANG_LANGUAGE_SAS": [".sas"],
    "TGLANG_LANGUAGE_SCALA": [".scala"],
    "TGLANG_LANGUAGE_SCHEME": [".scm", ".ss"],
    "TGLANG_LANGUAGE_SHELL": [".sh", ".bash", ".zsh"],
    "TGLANG_LANGUAGE_SMALLTALK": [".st"],
    "TGLANG_LANGUAGE_SOLIDITY": [".sol"],
    "TGLANG_LANGUAGE_SQL": [".sql"],
    "TGLANG_LANGUAGE_SWIFT": [".swift"],
    "TGLANG_LANGUAGE_TCL": [".tcl"],
    "TGLANG_LANGUAGE_TEXTILE": [".textile"],
    "TGLANG_LANGUAGE_TL": [".tl"],
    "TGLANG_LANGUAGE_TYPESCRIPT": [".ts", ".tsx"],
    "TGLANG_LANGUAGE_UNREALSCRIPT": [".uc"],
    "TGLANG_LANGUAGE_VALA": [".vala", ".vapi"],
    "TGLANG_LANGUAGE_VBSCRIPT": [".vbs"],
    "TGLANG_LANGUAGE_VERILOG": [".v", ".sv", ".svh"],
    "TGLANG_LANGUAGE_VISUAL_BASIC": [".vb"],
    "TGLANG_LANGUAGE_WOLFRAM": [".m", ".wl", ".wls"],
    "TGLANG_LANGUAGE_XML": [".xml", ".xsl", ".xsd", ".xslt", ".wsdl"],
    "TGLANG_LANGUAGE_YAML": [".yml", ".yaml"],
}
